#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
import os
from pathlib import Path

def createHeader(val):
    val = val.split("\n")
    stringVal = '#define VERSION        "'+val[0]+'"'
    return stringVal

def getVersion():
    f = open(os.path.join(proDir, "version"), "r")
    readVal = f.readline()
    f.close()
    h = open(os.path.join(proDir, "apps/libs/version.h"), "w")
    h.write(createHeader(readVal))
    h.close()

proDir = Path().parent.resolve()
sys.path.append(str(proDir)+'/iot/.platformio')

from platformio.__main__ import main
if __name__ == '__main__':
    getVersion()
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
