#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from pathlib import Path

proDir = Path().parent.resolve()
sys.path.append(str(proDir)+'/bin/iot/.platformio')
def createHeader(val):
    val = val.split("\n")
    stringVal = '#define VERSION        "'+val[0]+'"'
    return stringVal

def getVersion():
    f = open("version", "r")
    readVal = f.readline()
    f.close()
    h = open("iot/libs/version.h", "w")
    h.write(createHeader(readVal))
    h.close()

from platformio.__main__ import main
if __name__ == '__main__':
    getVersion()
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
